#!/usr/bin/env python3
"""node-reputation: bounded read-only config/state checker for node-reputation

Bounded read-only skill — replaces generic runtime with real logic.
Generated by mass_convert (wave runner, 2026-07-14).
"""
import json, subprocess, sys, os, re
from datetime import datetime, timezone
from pathlib import Path
from collections import Counter

def now(): return datetime.now(timezone.utc).isoformat()

CONFIG_PATHS = [
    "/etc/octopus/human_consent.env",
    "/etc/octopus/mesh_nodes.json",
    "/run/octopus/autonomy_state.json",
    "/etc/octopus/secrets.env",
]
def run():
    findings = []
    results = []
    for p in CONFIG_PATHS:
        path = Path(p)
        if path.exists():
            try:
                txt = path.read_text(errors="replace")
                if p.endswith(".json"):
                    data = json.loads(txt)
                    results.append({"path": p, "exists": True, "valid": True, "keys": list(data.keys())[:5] if isinstance(data, dict) else "list"})
                else:
                    results.append({"path": p, "exists": True, "lines": len(txt.splitlines())})
            except Exception as e:
                results.append({"path": p, "exists": True, "error": str(e)[:80]})
        else:
            results.append({"path": p, "exists": False})
            findings.append({"severity": "low", "path": p, "issue": "missing"})
    return {"ok": True, "configs": results, "findings": findings,
            "summary": {"checked": len(CONFIG_PATHS), "found": sum(r.get("exists", False) for r in results)}}

def main():
    data = run()
    data["skill"] = "node-reputation"
    data["timestamp"] = now()
    data["read_only"] = True
    print(json.dumps(data, ensure_ascii=False, indent=2))
    return 0 if data.get("ok", True) else 1

if __name__ == "__main__":
    sys.exit(main())
