#!/usr/bin/env python3
"""p2p-federation: bounded read-only service checker for p2p-federation

Bounded read-only skill — replaces generic runtime with real logic.
Generated by mass_convert (wave runner, 2026-07-14).
"""
import json, subprocess, sys, os, re
from datetime import datetime, timezone
from pathlib import Path
from collections import Counter

def now(): return datetime.now(timezone.utc).isoformat()

SERVICE_PREFIX = ""

def run():
    findings = []
    r = subprocess.run(["systemctl", "list-units", "--type=service", "--all",
                        "--no-legend", "--no-pager"], capture_output=True, text=True, timeout=10)
    relevant = []
    for line in r.stdout.splitlines():
        parts = line.split()
        if len(parts) < 4: continue
        svc = parts[0]
        active = parts[3]
        if "p2p" in svc.lower() or SERVICE_PREFIX in svc:
            relevant.append({"name": svc, "active": active})
            if active == "failed":
                findings.append({"severity": "high", "service": svc, "issue": "failed"})
    ok = not any(f["severity"] == "high" for f in findings)
    return {"ok": ok, "services": relevant[:15], "findings": findings[:5],
            "summary": {"found": len(relevant), "failed": sum(s["active"] == "failed" for s in relevant)}}

def main():
    data = run()
    data["skill"] = "p2p-federation"
    data["timestamp"] = now()
    data["read_only"] = True
    print(json.dumps(data, ensure_ascii=False, indent=2))
    return 0 if data.get("ok", True) else 1

if __name__ == "__main__":
    sys.exit(main())
