version: "3.8"
services:
  github_runner:
    image: alpine:latest
    command: ["tail", "-f", "/dev/null"]
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
