version: "3.8"
services:
  ipfs_node:
    image: ipfs/kubo:latest
    ports:
      - "4001:4001" # P2P TCP
      - "4001:4001/udp" # P2P UDP
      - "127.0.0.1:5001:5001" # API
      - "127.0.0.1:8080:8080" # Gateway
    volumes:
      - /root/agents/-Octopus/data/ipfs_staging:/export
      - /root/agents/-Octopus/data/ipfs_data:/data/ipfs
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
