#!/usr/bin/env python3
"""bft-lite: bounded read-only swarm/node status for bft-lite

Bounded read-only skill — replaces generic runtime with real logic.
Generated by mass_convert (wave runner, 2026-07-14).
"""
import json, subprocess, sys, os, re
from datetime import datetime, timezone
from pathlib import Path
from collections import Counter

def now(): return datetime.now(timezone.utc).isoformat()

def run():
    # Read mesh_nodes.json
    nodes = []
    mesh_path = Path("/etc/octopus/mesh_nodes.json")
    if mesh_path.exists():
        try:
            data = json.loads(mesh_path.read_text())
            for ip, info in data.items():
                nodes.append({"ip": ip, "hostname": info.get("hostname"),
                              "last_seen": info.get("last_seen")})
        except: pass
    # Check running swarm services
    r = subprocess.run(["systemctl", "list-units", "--type=service", "--state=active",
                        "--no-legend", "--no-pager"], capture_output=True, text=True, timeout=8)
    swarm_svcs = [l.split()[0] for l in r.stdout.splitlines()
                  if "swarm" in l.lower() or "node" in l.lower() or "sync" in l.lower()]
    return {"ok": True, "known_nodes": len(nodes), "nodes": nodes[:5],
            "active_swarm_services": swarm_svcs[:5],
            "summary": {"nodes": len(nodes), "services": len(swarm_svcs)}}

def main():
    data = run()
    data["skill"] = "bft-lite"
    data["timestamp"] = now()
    data["read_only"] = True
    print(json.dumps(data, ensure_ascii=False, indent=2))
    return 0 if data.get("ok", True) else 1

if __name__ == "__main__":
    sys.exit(main())
