# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aios.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'aios.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\naios.proto\x12\x04\x61ios\"}\n\x0bTaskRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x10\n\x08\x61gent_id\x18\x03 \x01(\t\x12\x12\n\nrisk_level\x18\x04 \x01(\t\x12\x11\n\ttenant_id\x18\x05 \x01(\t\x12\x12\n\nsteps_json\x18\x06 \x01(\t\"/\n\x0cTaskResponse\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\"$\n\x11TaskStatusRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\"Y\n\x12TaskStatusResponse\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x13\n\x0bresult_json\x18\x03 \x01(\t\x12\r\n\x05\x65rror\x18\x04 \x01(\t\"\x0e\n\x0cStatsRequest\"#\n\rStatsResponse\x12\x12\n\nstats_json\x18\x01 \x01(\t2\xb8\x01\n\x08\x41iosCore\x12\x33\n\nSubmitTask\x12\x11.aios.TaskRequest\x1a\x12.aios.TaskResponse\x12\x42\n\rGetTaskStatus\x12\x17.aios.TaskStatusRequest\x1a\x18.aios.TaskStatusResponse\x12\x33\n\x08GetStats\x12\x12.aios.StatsRequest\x1a\x13.aios.StatsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aios_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TASKREQUEST']._serialized_start=20
  _globals['_TASKREQUEST']._serialized_end=145
  _globals['_TASKRESPONSE']._serialized_start=147
  _globals['_TASKRESPONSE']._serialized_end=194
  _globals['_TASKSTATUSREQUEST']._serialized_start=196
  _globals['_TASKSTATUSREQUEST']._serialized_end=232
  _globals['_TASKSTATUSRESPONSE']._serialized_start=234
  _globals['_TASKSTATUSRESPONSE']._serialized_end=323
  _globals['_STATSREQUEST']._serialized_start=325
  _globals['_STATSREQUEST']._serialized_end=339
  _globals['_STATSRESPONSE']._serialized_start=341
  _globals['_STATSRESPONSE']._serialized_end=376
  _globals['_AIOSCORE']._serialized_start=379
  _globals['_AIOSCORE']._serialized_end=563
# @@protoc_insertion_point(module_scope)
